version: '3.8'

services:
  # The NestJS application service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    ports:
      # Maps host port 3100 to container port 3000
      - '3100:3000'
    depends_on:
      # This links the API service to the external PostgreSQL container
      - my-postgres-db
    environment:
      DATABASE_URL: 'postgresql://developer:developer@postgres-server:5432/icara?schema=public'
      PORT: 3000
    networks:
      - my-network

# Define the external network
networks:
  my-network:
    external: true